version: '2'
services:
    app:
        build:
            context: "./app"
        ports:
            - "8080:8080"
    db:
        build:
            context: "./db"
        container_name: 'twitclone-db'
        ports:
            - "3306:3306"
