version: '2'
services:
    app:
        build: .
        ports:
            - "8080:8080"
    db:
        image: 'mysql:8.0.0'
        command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        ports:
            - "3306:3306"
