version: '2'
services:
    app:
        extends:
            file: 'basic.yml'
            service: app
        container_name: 'twitclone-dev-app'
        command: 'bash -c "cd dev && nodemon -V server.js"'
        depends_on:
            - db
        volumes:
            - './app/src:/opt/twitclone/dev/'
    db:
        extends:
            file: 'basic.yml'
            service: db
        volumes:
            - 'twit-dev-db:/var/lib/mysql'
    dbadmin:
        image: 'phpmyadmin/phpmyadmin:4.6'
        container_name: 'twitclone-db-admin'
        depends_on:
            - db
        environment:
            PMA_HOST: 'twitclone-db'
        ports:
            - "80:80"
volumes:
    twit-dev-db:
